stages:
    - build

build_project:
    stage: build
    script:

        - xcodebuild clean -workspace StrawberryPie.xcworkspace -scheme StrawberryPie | xcpretty
        - xcodebuild test -workspace StrawberryPie.xcworkspace -scheme StrawberryPie -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' | xcpretty -s


    tags:
    - strawberrypie
    - iosdev
    - tyokkari

